
/*
    Domain-Specific, concrete routing rules.
    Can exploit JsonPath / XPath queries on a message's
    encoded form for type-unsafe checks, in addition to
    standard pattern matching on a message content
    represented in object form

*/


package org.drools.mas;

import org.drools.mas.Destination;
import org.drools.mas.SessionMapping;
import org.drools.mas.ACLMessage;
import org.drools.mas.util.ACLMessageFactory;
import org.drools.mas.body.acts.Inform;
import org.drools.mas.body.content.*;
import org.drools.mas.util.InspectMessageHelper;




rule "Mapping"
when
then
    insert( new SessionMapping("action-selection-primary","session1") );
    
end


rule "Route_Encoded_JSON"
when
    $msg : ACLMessage( $msgId : id, $b : body, encoding == Encodings.JSON  )
    ?mapSession( "action-selection-primary" , $sessionId ; )
then
    System.out.println("Routing message " + $msgId + " (JSON)" );
    insertLogical( new Destination($msgId, $sessionId) );
end

rule "Route_Encoded_XML"

when
    $msg : ACLMessage( $msgId : id, $b : body, encoding == Encodings.XML )
    ?mapSession( "action-selection-primary" , $sessionId ; )
then
    System.out.println("Routing message " + $msgId + " (XML)"  );
    insertLogical( new Destination($msgId, $sessionId) );
end




