package org.drools.mas;

import org.drools.mas.body.content.*;
import org.drools.mas.action.message.*;
import org.drools.mas.action.message.types.*;
import org.drools.mas.action.message.invokers.*;
import org.drools.mas.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.Date;
import org.drools.mas.util.MessageContentEncoder;
import org.drools.mas.action.helpers.*;


import javax.xml.ws.BindingProvider;


global java.util.Map channels;


declare Entity
    @Traitable
    id                  : String        @key
    resolved            : boolean                   = false
    cn                  : String
    mobile              : String
    employeeNumber      : String
    displayName         : String
    gender              : String
end


declare trait OrgEntity

    cn                  : String
    mobile              : String
    employeeNumber      : String
    displayName         : String
    gender              : String
end

declare trait Patient extends OrgEntity

    id                  : String        @key
    messageId           : String
end

declare trait Provider extends OrgEntity

    id                  : String        @key
    messageId           : String
end

declare trait Recipient extends OrgEntity

    id                  : String        @key
    messageId           : String
end

declare trait MainRecipient extends Recipient

end

declare trait SecondaryRecipient extends Recipient

end

declare trait HiddenRecipient extends Recipient

end







declare DeliverableMessage
    id                  : String        @key
end

declare SMSMessage extends DeliverableMessage
    mobileNumber        : String
    text                : String
end

declare AlertMessage extends DeliverableMessage
    ticketId            : String
    recipient           : String
    body                : String
end


declare MessageDeliveredResponse
    refId               : String        @key
    convoId             : String        @key
end


rule "ENTER"
salience 99999
when
    $o : Object()
then
    System.out.println("************************************************* " + $o );
end

rule "Q"
salience 99999
when
    $o : org.drools.base.DroolsQuery( )
then
    System.out.println("********************QRYYY***************************** " + $o );
end

// totally useless rule, except for debug :)
rule "Deliver Message Action Found"
    when
        $action: Action( actionName == "deliverMessage",
                          $refId   : this["refId"],
                          $convoId : this["conversationId"]
                        )
        $old : MessageDeliveredResponse( refId != $refId || convoId != $convoId )
    then
        System.out.println("!!!! Action RefId >>> " + $refId );
        System.out.println("!!!! Action ConvoId >>> " + $convoId );
end


//TODO : remove when delivery will generate the resp
rule "Deliver Message Action Reset Result"
    when
        $action: Action( actionName == "deliverMessage",
                          $refId   : this["refId"],
                          $convoId : this["conversationId"]
                        )
    then
        insert( new MessageDeliveredResponse( (String) $refId, (String) $convoId ) );
end





rule "Deliver Message Action Reset Result - Clean"
    when
        $action: Action( actionName == "deliverMessage",
                          $refId   : this["refId"],
                          $convoId : this["conversationId"]
                        )
        $old : MessageDeliveredResponse( refId != $refId || convoId != $convoId )
    then
        retract( $old );
end


rule "Clean Deliver Message Action"
salience -999
    when
        $action: Action( actionName == "deliverMessage" )
    then
        retract( $action );
end









rule "Insert Subject-About Entities"
    when
        $action: Action( actionName == "deliverMessage",
                         $refId        : this["refId"],
                         $cnvId        : this["conversationId"],
                         $subjectAbout : this["subjectAbout"]
                       )
        $id : String() from $subjectAbout
    then
        insertLogical( new Entity( $id ) );
end


rule "Resolve"
when
    $ent : Entity( $id : id, resolved == false )
then
    System.out.println( "I'm calling the LDAP Service here for " + $id );
    // TOOD : CALL LDAP SERVICE HERE!

        $ent.setCn( "cn_" + $id );
        $ent.setMobile( "mob_00" + $id );
        $ent.setEmployeeNumber( "empNum_" + $id );
        $ent.setDisplayName( "name_" + $id );
        $ent.setGender( "x" );

    $ent.setResolved( true );
    update( $ent );
end


rule "Resolve Patient"
when
    $action: Action( actionName == "deliverMessage",
                         $refId : this["refId"],
                         $cnvId : this["conversationId"],
                         $subjectAbout : this["subjectAbout"]
                       )
    $pid : String() from ( (String[]) $subjectAbout )[0]
    $ent : Entity( id == $pid, resolved == true )
then
    System.out.println( "The patient ID IS  " + $pid );
    Patient pat = don( $ent, Patient.class, true );
        pat.setMessageId( (String) $cnvId );
    update( pat );
end


rule "Resolve Main Recipients"
when
    $action: Action( actionName == "deliverMessage",
                         $refId      : this["refId"],
                         $cnvId      : this["conversationId"],
                         $recipients : this["mainRecipients"]
                       )
    $rid : String() from ( (String[]) $recipients )
    $ent : Entity( id == $rid, resolved == true )
then
    System.out.println( "The recipient ID IS  " + $rid );
    MainRecipient rec = don( $ent, MainRecipient.class, true );
        rec.setMessageId( (String) $cnvId );
    update( rec );
end


rule "Resolve Sender as Provider"
when
    $action: Action( actionName == "deliverMessage",
                         $refId      : this["refId"],
                         $cnvId      : this["conversationId"],
                         $sender     : this["sender"]
                       )
    $ent : Entity( id == $sender, resolved == true )
then
    System.out.println( "The provider ID IS  " + $sender );
    Provider pro = don( $ent, Provider.class, true );
    System.out.println( pro.hashCode() );
        pro.setMessageId( (String) $cnvId );
    System.out.println( pro.hashCode() );
    update( pro );
end




//    $action: Action( actionName == "deliverMessage",
//                        $refId          : this["refId"],
//                        $convoId        : this["conversationId"],
//                        $about          : this["subjectAbout"],
//                        $mainRec        : this["mainRecipients"],
//                        $secRec         : this["secondaryRecipients"],
//                        $hiddenRec      : this["hiddenRecipients"],
//                        $type           : this["type"],
//                        $header         : this["header"],
//                        $body           : this["body"],
//                        $priority       : this["priority"],
//                        $deliveryDate   : this["deliveryDate"],
//                        $status         : this["status"]
//                   )



rule "Construct SMS"
when
    $action: Action( actionName == "deliverMessage",
                        $refId          : this["refId"],
                        $convoId        : this["conversationId"],
                        $type           : this["type"] == "SMS",
                        $header         : this["header"]
                   )
    $rec :   Recipient( messageId == $convoId, $mobile : mobile )
then
    insert( new SMSMessage( (String) $convoId, $mobile, (String) $header ) );
end



   rule "Construct SMS2"
   when
       $action: Action( actionName == "deliverMessage",
                           $refId          : this["refId"],
                           $convoId        : this["conversationId"],
                           $type           : this["type"] == "SMS",
                           $header         : this["header"]
                      )
       $rec :   Recipient( messageId == $convoId, $mobile : mobile )
   then
       //insert( new SMSMessage( (String) $convoId, $mobile, (String) $header ) );
      // DeliverMessageHelper.sendSMS("http://192.168.5.47:8080/PresentationServices/DSAIntegration?WSDL", $mobile, (String) $header );
       System.out.println("Delivering (send sms) Message with arguments =  "+
                                              "URL = " + "http://192.168.5.47:8080/PresentationServices/DSAIntegration?WSDL" +
   	                                      " mobile = "+  $mobile +
   	                                      " header = " + (String) $header 
                );  
   end



   rule "Construct Alert Body"
       when
           $action: Action( actionName == "deliverMessage",
                           $refId          : this["refId"],
                           $convoId        : this["conversationId"],
                           $about          : this["subjectAbout"],
   			               $sender		   : this["sender"],
                           $mainRec        : this["mainRecipients"],
                           $secRec         : this["secondaryRecipients"],
                           $hiddenRec      : this["hiddenRecipients"],
                           $type           : this["type"] == "ALERT",
                           $header         : this["header"],
                           $body           : this["body"],
                           $priority       : this["priority"],
                           $deliveryDate   : this["deliveryDate"],
                           $status         : this["status"]
                          )
           $pat :   Patient( messageId == $convoId )
           $pro :   Provider( messageId == $convoId )
           $rec :   Recipient( messageId == $convoId )
       then
           Map args = new HashMap();
               args.put( "recipient", $rec );
               args.put( "patient", $pat );
               args.put( "provider", $pro );

           String finalBody = (String) org.mvel2.templates.TemplateRuntime.execute( org.mvel2.templates.TemplateCompiler.compileTemplate( (String) $body ), args );
        //   DeliverMessageHelper.sendAlert( "http://192.168.5.47:8080/PresentationServices/DSAIntegration?WSDL",
        //                                   (String) $convoId,
        //                                   (String) $header,
        //                                   finalBody,
        //                                   (String) $sender,
        //                                   $rec.getId(),
        //                                   $about );
          System.out.println("Delivering (send alert) Message with arguments =  "+
                                              "URL = " + "http://192.168.5.47:8080/PresentationServices/DSAIntegration?WSDL" +
   	                                      " convoId = "+  (String) $convoId +
   	                                      " header = " + (String) $header +
                                              " final body  =" + finalBody +  
   	                                      " sender = " +  (String) $sender + 
   	                                      " rec.id = " +  $rec.getId() +
                                              " about  = " + $about  
                );                                 
   end



   rule "Construct Update Body"
       when
           $action: Action( actionName == "deliverMessage",
                           $refId          : this["refId"],
   			               $sender		: this["sender"],
                           $convoId        : this["conversationId"],
                           $type           : this["type"] == "UPDATE",
                           $priority       : this["priority"],
                           $deliveryDate   : this["deliveryDate"],
                           $status         : this["status"],
                           $header         : this["header"]
                          )
           $rec :   Recipient( messageId == $convoId )
       then
   	       // DeliverMessageHelper.sendAlert( "http://192.168.5.47:8080/PresentationServices/DSAIntegration?WSDL",
   	       //                                 (String) $convoId,
   	       //                                 (String) $header,
   	       //                                 (String) $status,
   	       //                                 (String) $sender,
   	       //                                 $rec.getId() );
               System.out.println("Delivering (send alert) Message with arguments =  "+
                                              "URL = " + "http://192.168.5.47:8080/PresentationServices/DSAIntegration?WSDL" +
   	                                      " convoId = "+  (String) $convoId +
   	                                      " header = " + (String) $header +
   	                                      " status = " + (String) $status +
   	                                      " sender = " +  (String) $sender + 
   	                                      " rec.id = " +  $rec.getId()
                );
   end







query deliverMessage( String $refId, String $conversationId,
                      String $subjectabout,
                      String $sender, String $mainRecipients, String $secondaryRecipients, String $hiddenRecipients,
                      String $type, String $header, String $body,
                      String $priority,
                      String $deliveryDate, String $status,
                      String $return )
       $ret : MessageDeliveredResponse( $refId, $conversationId; )
       $return:= String() from MessageContentEncoder.encode($ret, Encodings.XML);
end


