
/*
 * TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
 * Copyright (c) 2008, Nationwide Health Information Network (NHIN) Connect.
 * All rights reserved.Redistribution and use in source and binary forms,
 * with or without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 * - Neither the name of the NHIN Connect Project nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *    END OF TERMS AND CONDITIONS
 */

package gov.hhs.fha.nhinc.kmr2.clinicalAgent.models.decision;

import org.drools.informer.generator.Surveyable;

import org.drools.informer.generator.annotations.Questionable;
import org.drools.informer.generator.annotations.QuestionMark;
import org.drools.informer.generator.annotations.AllowedAnswers;


declare DiagnosticGuideProcess
   id                       : String                @key
   status                   : String                        = "N/A"
   decModel                 : String
   diagModel                : String
   disease                  : String
   diagnosticProcessHistory : java.util.LinkedList
   canAdvance               : boolean                       = false
   canCancel                : boolean                       = false
   actions                  : java.util.HashSet
   taskId                   : String
end


declare DxDecision
    nodeId                  : String                @key
    stage                   : int
    current                 : boolean
    descr                   : String
    diseaseProbability      : int                  = -1
    diseaseProbabilityReal  : double               = -1.0
    severity                : String
    response                : String
    actions                 : java.util.List
end



declare Surveyable
@typesafe( false )
end


declare DxAction
@typesafe( false )

    actionId        : String                        @key
    dxProcessId     : String
    step            : int

    taskId          : String
    // control questionnaire, allows to se the task State
    questionnaireId : String

    status          : String                        = "Not Started"
    statusUpdated   : String

    numQuestions    : int
    body            : String
    bodyQuestId     : String

    utility         : double                        = -1.0
    rndUtility      : int                           = -1
    utilityLevel    : String                        = "N/A"

end



declare DxStep
    dxProcessId : String
    stage       : int
end


declare trait DiagValue
    value   : double
    context : String
end




query isUseful( DxAction $act, Double $use, Integer $intg )
    $use := Double() from ( 0.01 * Math.round( 100 * Math.random() ) )
    $intg := Integer() from new Integer( Math.round( 100 * $use ) )
end















